### ISSUE TITLE
Questions about source

### ISSUE THREAD

**Issue by pwntester** [Shougo/deoplete-lsp#14]
Hi,

Before sending a PR for this, is there a good reason for:
- removing brackets [here](https://github.com/Shougo/deoplete-lsp/blob/master/rplugin/python3/deoplete/source/lsp.py#L100)
- not filling `item['menu']` with `rec['detail']` [here](https://github.com/Shougo/deoplete-lsp/blob/master/rplugin/python3/deoplete/source/lsp.py#L109)

thanks

**Comment by Shougo** [comment]
Please describe why the changes are needed.

**Comment by pwntester** [comment]
The first one may be asethetics, but if the server sends a candidate for completion, I dont see a reason to change it. In my case, I find myself adding th brackets that this source removes.

For the second one, the LSP completion Im getting from the server look like:

```
...
            "label":"getLocation",
            "kind":2,
            "detail":"Location getLocation() - Top",
            "documentation":{
               "kind":"markdown",
               "value":" Gets the source location for this element."
            },
            "insertText":"getLocation()",
            "insertTextFormat":1,
...
```

I think, `detail` is short enough to be included as the `menu` description so we get context right away. `documentation.value` is the one that I think should be shown as the `info` element (shown in the preview window).

As you can see in the example below, the proposed candidate contains `()` which this source remove and that I need to enter myself.

As a curiosity, does deoplete or neosnippet support placeholders? what if the candidate is `getlocation($1)`, is there a way to move the cursor to the tabstop after expanding the completion?

Thanks!

**Comment by pwntester** [comment]
As expained [here](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion), `documentation` is optional and my require a second request to the server, but I still think this is the kind of info for the preview window, while `detail` is more suitable for the `menu`

**Comment by Shougo** [comment]
> The first one may be asethetics, but if the server sends a candidate for completion, I dont see a reason to change it. In my case, I find myself adding th brackets that this source removes.

OK.

> I think, detail is short enough to be included as the menu description so we get context right away. documentation.value is the one that I think should be shown as the info element (shown in the preview window).

Ah, OK.  Please add documentation support as `menu` instead.

**Comment by Shougo** [comment]
> As a curiosity, does deoplete or neosnippet support placeholders? what if the candidate is getlocation($1), is there a way to move the cursor to the tabstop after expanding the completion?

It is possible.  Please set `snippet` dictionary as `user_data`.

The `user_data` is decoded like this.

```vim
function! s:get_user_data(cur_text) abort
  let user_data = json_decode(v:completed_item.user_data)
  if type(user_data) !=# v:t_dict
    return []
  endif

  let cur_text = a:cur_text

  if get(user_data, 'snippet', '') !=# ''
    let snippet = user_data.snippet
    let snippet_trigger = get(user_data, 'snippet_trigger',
          \ v:completed_item.word)
    let cur_text = cur_text[: -1-len(snippet_trigger)]
    return [cur_text, snippet, {'lspitem': has_key(user_data, 'lspitem')}]
  endif

  return []
endfunction
```

Note:  To expand it, you need to set `g:neosnippet#enable_complete_done`.
