### ISSUE TITLE
Add textEdit handling

### ISSUE THREAD

**Issue by Weypare** [Shougo/deoplete-lsp#20]
At the moment, the textEdit field of CompletionItem is not [handled](https://github.com/Shougo/deoplete-lsp/blob/master/rplugin/python3/deoplete/source/lsp.py#L91-L97). This causes completion of the labels instead of actual completion words.

Completion items:
![image](https://user-images.githubusercontent.com/17096718/75587704-beffc100-5a7f-11ea-8c43-d8df1cefb125.png)
After completion confirmation:
![image](https://user-images.githubusercontent.com/17096718/75587747-d6d74500-5a7f-11ea-8156-6875fe557a6a.png)

According to the LSP specification:
```
/**
  * An edit which is applied to a document when selecting this completion. When an edit is provided the value of
  * `insertText` is ignored.
  *
  * *Note:* The range of the edit must be a single line range and it must contain the position at which completion
  * has been requested.
  */
textEdit?: TextEdit;
```

**Comment by Shougo** [comment]
You can add the feature if it is needed.
This is open source.
