### ISSUE TITLE
about deoplete-lsp/jedi and caching

### ISSUE THREAD

**Issue by astier** [Shougo/deoplete-lsp#28]
I am playing around with `deoplete-lsp` and `deoplete-jedi`. I noticed that when I try to autocomplete from the python-module `numpy` both take a little bit of time to load because numpy is big, although jedi is a little bit faster. However, what I noticed is that when I try to load the same completions a second time deoplete-jedi is a lot faster, whereas deoplete-lsp takes approximately the same amount of time as the first time.

Is there some caching going on? If so does deoplete-jedi or jedi itself does the caching?

I am using `nvim v0.5.0 1153ac903`

### Minimal vimrc - deoplete-lsp

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'Shougo/deoplete-lsp'
    Plug 'neovim/nvim-lsp'
cal plug#end()
lua require'nvim_lsp'.pyls.setup{}
let g:deoplete#enable_at_startup = 1
cal deoplete#custom#option({'min_pattern_length': 1})
se completeopt=menuone,noinsert
```

### Minimal vimrc - deoplete-jedi

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'deoplete-plugins/deoplete-jedi'
cal plug#end()
let g:deoplete#enable_at_startup = 1
cal deoplete#custom#option({'min_pattern_length': 1})
se completeopt=menuone,noinsert
```

### Minimal python-file

```python
import numpy
numpy
```

### Steps to reproduce

1. `pip install numpy`
2. Create minimal python-file
3. Type `.` after last `numpy` and wait for the completion to show up
4. Delete `.` and type `.` again to trigger completion again

It can be observed that deoplete-jedi takes less time to reload the same results the second time, whereas deoplete-lsp needs approximately the same amount of time.

**Comment by astier** [comment]
Nevermind. Its an issue with pyls. https://github.com/palantir/python-language-server/issues/823

**Comment by Shougo** [comment]
OK
