### ISSUE TITLE
Error detected while processing InsertEnter Autocommands for "*":

### ISSUE THREAD

**Issue by Masterchef365** [Shougo/deoplete-lsp#41]
# Problems summary
When any type of Insert command is used, `Error detected while processing InsertEnter Autocommands for "*":` interrupts editing

## Environment Information
 * deoplete and deoplete-lsp version (SHA1): 134e970130d57c6683052a506776fa12e04bd3de
 * OS: Both Arch Linux x64, and Ubuntu 18.04 x64
 * neovim/Vim `:version` output:
```
NVIM v0.5.0-617-g82bfdbfe5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
or
```
NVIM v0.5.0-828-g0a95549d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
``` 
(happens on both)

 * `:checkhealth` or `:CheckHealth` result(neovim only):
https://hastebin.com/ixijupofev.txt

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```vim
" Your minimal init.vim/vimrc
call plug#begin('~/.config/nvim/bundle')
Plug 'Shougo/deoplete-lsp'
call plug#end()
let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)
Simply open the editor and use an insert command such as `i`

## Generate a logfile if appropriate
```
Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'hover'
```
This seems suspiciously simple, so I assume it's something I'm doing wrong - however before an update it was working on two separate Linux machines, and now it works on neither. Last working commit is fb51bfebd8ac57282154d119f80368b4b94199b7, and downgrading to that version fixes the issue.

**Comment by Shougo** [comment]
It because the PR https://github.com/Shougo/deoplete-lsp/pull/40.

You need to the latest version of neovim.
Your neovim version is unfortunately old.

**Comment by Shougo** [comment]
Please read this.

>Merging this PR will cause problems for users who use the older version of neovim.

**Comment by Masterchef365** [comment]
Oh wow, okay. I thought the version released 9 days ago would have been recent enough. Thanks!
