### ISSUE TITLE
hover.lua `handlers` replaced with `callbacks`

### ISSUE THREAD

**Issue by alexb7711** [Shougo/deoplete-lsp#42]
OS: Arch linux
NVIM v0.5.0-828-g0a95549d6

I updated my computer and handlers.lua started throwing errors. After looking into it, it looks like that `vim.handlers` was replaced with `vim.callbacks`. Updating `hover.lua` with the new callback method, it gets rid of the error and works again.

![`vim.handlers` error](https://user-images.githubusercontent.com/42049885/99883947-bd66c200-2be7-11eb-90e7-03d521604709.png)

![help menu for vim.lsp](https://user-images.githubusercontent.com/42049885/99883995-0dde1f80-2be8-11eb-8f59-6e8767acb64c.png)

**Comment by bew** [comment]
https://github.com/Shougo/deoplete-lsp/issues/41

**Comment by alexb7711** [comment]
My bad, didn't see that. Thanks!
