### ISSUE TITLE
Feature request: Disable Hover

### ISSUE THREAD

**Issue by cideM** [Shougo/deoplete-lsp#43]
This commit https://github.com/Shougo/deoplete-lsp/commit/90d7b3a92a9cb11b76386542dabf3e3c9fd750e4 added a hover window which you can't disable or configure in any way. Would it be possible to add an option that let's people opt out of this feature?

**Comment by Shougo** [comment]
You can disable it by `autocmd! deoplete#lsp` after deoplete initialized.
