### ISSUE TITLE
completion-items filtering

### ISSUE THREAD

**Issue by pwang2** [Shougo/deoplete-lsp#44]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Not sure if this is the right place to post.  I was trying to migrate from 3rd party LSP client to nvim 5.0's LSP client, it mostly works fine with small files, but with big files, all the global variables, object fields seem being filled to complete-items dictionary as **File [lsp]**

## Expected
be able to rank and filter out the dictionary from LSP.

## Environment Information

 * deoplete and deoplete-lsp version (SHA1):
 >134e970130d57c6683052a506776fa12e04bd3de 
 * OS:
 >MacOS 11
 * neovim/Vim `:version` output:
```
NVIM v0.5.0-dev+nightly-279-g84faeb07d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201225-31318-r5eqpv/build/config -I/tmp/neovim-20201225-31318-r5eqpv/src -I/usr/local/include -I/tmp/neovim-20201225-31318-r5eqpv/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201225-31318-r5eqpv/build/src/nvim/auto -I/tmp/neovim-20201225-31318-r5eqpv/build/include

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-84faeb0/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
https://gist.github.com/96bf8c7f02a66b56da2476a7e60153c6

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```
call plug#begin()
  Plug 'neovim/nvim-lspconfig'
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  Plug 'Shougo/deoplete-lsp'
call plug#end()

let g:deoplete#enable_at_startup          = 1

call deoplete#custom#option('sources', {
\ '_': ['buffer'],
\ 'javascript': ['lsp']
\})

:lua <<EOF
require'lspconfig'.tsserver.setup{}
EOF
```
## How to reproduce the problem from neovim/Vim startup (Required!)

 1. create an empty folder `test` with an empty package.json
 2. create a new file abc.js under that folder
 3. create a javascript object as following
  ```
    const testObj = {a: 1, b: Symbol() }
  ```
 4. type testObj and a dot to see the completion.
 5. if the file is biger, the whoe completion list will be full with **File [Lsp]**

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/1592014/103146406-671cff80-470e-11eb-9403-8288b283db3a.png)

**Comment by Shougo** [comment]
You can use `converter_reorder_attr` for it.
`:help deoplete-filter-converter_reorder_attr`

Hint: `File [lsp]` is `File` kind.

**Comment by pwang2** [comment]
Thanks for reply.
I have tried that. but it seems make no difference. 
![image](https://user-images.githubusercontent.com/1592014/103153226-b423c480-4754-11eb-9e0d-1d6eb50cf376.png)

**Comment by Shougo** [comment]
Oh, you don't know deoplete filter's behavior.
You must set filter for lsp source.
Please read the documenataion.

```vim
		call deoplete#custom#source('lsp', 'converters',
		\ ['converter_reorder_attr'])
```

**Comment by pwang2** [comment]
Yes, I was kinda confused about the document here.  Thank you for your guidance. Everything works as expected now.
