### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by idanko** [Shougo/deoplete-lsp#5]
Hi. Following the deoplete-lsp documentation and after installing deoplete and deoplete-lsp on my newish neovim build v0.4.0-1257-g777cc6f98 (hopefully  with LSP feature), it reports `E117: Unknown function: lsp#server#add`
The documentation needs to be updated, thank you.

**Comment by Shougo** [comment]
>  it reports E117: Unknown function: lsp#server#add

It means your neovim is not enabled LSP feature.

> hopefully with LSP feature

LSP feature is not merged on master.
Why do you think LSP feature is enabled?

**Comment by Shougo** [comment]
`lsp#server#add()` exists on LSP PR.
https://github.com/neovim/neovim/pull/10222/files#diff-e012edaca0bf2c2c3644f3eee85d2038

**Comment by idanko** [comment]
> > it reports E117: Unknown function: lsp#server#add
> 
> It means your neovim is not enabled LSP feature.
> 
> > hopefully with LSP feature
> 
> LSP feature is not merged on master.
> Why do you think LSP feature is enabled?

Ah, my apologies didn't catch [PR](https://github.com/neovim/neovim/pull/10222) isn't merged yet

**Comment by Shougo** [comment]
Oh...
