### ISSUE TITLE
Feature Request: function-signature snippets

### ISSUE THREAD

**Issue by paulreimer** [Shougo/deoplete-lsp#7]
I currently use LanguageClient-neovim and with the `g:LanguageClient_hasSnippetSupport` feature (and then to neosnippet for snippet expansion).

It looks something like this:
![](https://user-images.githubusercontent.com/859939/59410679-cbae8d00-8dfc-11e9-99ac-f8d0bedcbfaa.png)

Now with the new neovim PR + the `textDocument/signatureHelp` feature, is this a feature for deoplete-lsp?

**Comment by Shougo** [comment]
It can be supported.

You can create the PR for it.

**Comment by amikai** [comment]
@Shougo Can you give some tips about how to do that. I want to try it.

**Comment by Shougo** [comment]
I think this feature is already supported by https://github.com/neovim/neovim/pull/12204.

**Comment by Shougo** [comment]
Hm.  The support is not related to deoplete-lsp.
It is neosnippet's work.  Please wait.

**Comment by paulreimer** [comment]
OK I will close this issue, if neosnippet is the better place for the feature (I would prefer that!).

**Comment by Shougo** [comment]
I have implemented it.
Please update neosnippet.
